version: 0.1
keywords: "HTML, Javascript, Visual Experience"
title: "Arc3"
description: "3D illusion of Karbandi"
url: "http://behrooz-tahanzadeh.github.io/arc3/"
date: "November 2014"
googleAnalyticsCode: "UA-40560087-5"
